### ISSUE TITLE
建议显示测不出或其他线路

### ISSUE THREAD

**Issue by spiritLHLS** [zhanghanyun/backtrace#3]
测试VPS，有的奇葩VPS测不出线路的，那一块全空，建议显示测不出或其他线路，不然空好几行没显示好难看
我测的IP: 45.155.76.194

**Comment by zhanghanyun** [comment]
fix https://github.com/zhanghanyun/backtrace/releases/tag/v1.0.5

**Comment by zhanghanyun** [comment]
fix [9bcda41](https://github.com/zhanghanyun/backtrace/commit/9bcda4140335d7c419f400232512d0803831a373)
