### ISSUE TITLE
AS58807 移动CMIN2-NET 优化线路 请求加入识别

### ISSUE THREAD

**Issue by spiritLHLS** [zhanghanyun/backtrace#6]
AS58807 移动CMIN2-NET 优化线路

请求加入识别

**Comment by taurusxin** [comment]
#7 试着加了一些58807的IP段，现在用着没啥问题

**Comment by spiritLHLS** [comment]
> #7 试着加了一些58807的IP段，现在用着没啥问题

感谢，近期很多商家要上架这种线路了，等一个merge就舒服了

**Comment by spiritLHLS** [comment]
由于作者没有空进行维护，已自行修复至于 https://github.com/oneclickvirt/backtrace
